CREATE TABLE TABELA_DE_CLIENTES(

CPF CHAR (11) ,
NOME VARCHAR (50),
RUA VARCHAR (50),
COMPLEMENTO VARCHAR (50),
BAIRRO VARCHAR (50),
ESTADO CHAR (2),
CEP CHAR (8),
DATA_DE_NASCIMENTO DATE,
IDADE SMALLINT,
SEXO CHAR (1),
LIMITE_DE_CREDITO MONEY,
VOLUME_MININO FLOAT,
PRIMEIRA_COMPRA BIT

);
/*O código de produto;
O nome do produto;
A embalagem;
O tamanho;
O sabor do suco;
E o preço de lista.*/

CREATE TABLE TABELA_DO_PRODUTO(

CODIGO_DO_PRODUTO VARCHAR (20) NOT NULL PRIMARY KEY,
NOME_DO_PRODUTO VARCHAR (50),
EMBALAGEM VARCHAR (20),
TAMANHO VARCHAR (20),
SABOR_DO_SUCO VARCHAR (20),
PRECO_DE_LISTA SMALLMONEY

);

/*ALTERANDO UM DADO DA TABELA, PRIMEIRO ESCOLHA A TABELA E DEPOIS A COLUNA QUE VOCÊ DESEJA ALTERAR, LEBRESSE DE COLOCAR O NOME DA COLUNA, O TIPO 
DELA E O TAMANHO E EM SEGUIDA COLOCAR O COMANDO QUE VOCÊ DESEJA REALIZAR*/
ALTER TABLE TABELA_DE_CLIENTES ALTER COLUMN CPF CHAR (11) NOT NULL;

/*A cláusula ADD CONSTRAINT é usada em linguagens SQL para adicionar restrições (constraints) a uma tabela existente.*/
/*CLUSTERED*/
ALTER TABLE TABELA_DE_CLIENTES ADD CONSTRAINT PK_TABELA_CLIENTE PRIMARY KEY CLUSTERED (CPF);

CREATE TABLE TABELA_DE_VENDEDORES(

MATRICULA VARCHAR (5),
NOME VARCHAR (100),
PERCENTUAL_COMISSAO FLOAT

);

/* Novo suco:
1040107
Light 350 ml - Melancia
Lata
350 ml
Melancia
R$ 4,56*/

INSERT INTO TABELA_DO_PRODUTO VALUES (
'123',
'Light 350 ml - Melância',
'Lata',
'350 ML',
'Melância',
4.56
);

/*INSERT INTO com a sintaxe VALUES para inserir dados em uma tabela de um banco de dados relacional.*/
INSERT INTO TABELA_DO_PRODUTO VALUES
('10837797', 'Clean - 2 Litros - Laranja', 'PET', '2 Litros', 'Laranja', 16.01), 
('1000889', 'Sabor da Montanha 700 ml Uva', 'Garrafa', '700 ml', 'Uva', 6.31),
('1004327', 'Videira do Campo 1,5 Litros Melancia', 'PET', '1,5 Litros', 'Melancia', 19.51),
('1088126', 'Linha Citrus 1 Litro Limão', 'PET', '1 Litro', 'Limão', 7.00);

INSERT INTO TABELA_DE_CLIENTES VALUES

('00111111555', 'Maria JULIA', 'Rua Projetada B', 'Número 2111', 'Copacabana', 'RJ', '20000000', '1995-06-21',47, 'F', 200000, 3000.30, 0),
('02384653433', 'GUILHERME', 'Rua Projetada C', 'Número 213', 'Copacabana', 'RJ', '20000000', '1965-03-14' ,57, 'M', 20000000, 3000.30, 1);


INSERT INTO TABELA_DO_PRODUTO
(CODIGO_DO_PRODUTO, NOME_DO_PRODUTO, EMBALAGEM, TAMANHO, PRECO_DE_LISTA, SABOR_DO_SUCO)
VALUES
('5449310', 'Frescor do Verão - 350 ml - Limão', 'Lata', '350 ml',2.45, 'Limão'),
('1078680', 'Frescor do Verão - 350 ml - Manga', 'Lata', '350 ml',3.18, 'Manga');

SELECT NOME, DATA_DE_NASCIMENTO 
 FROM TABELA_DE_CLIENTES;

 SELECT * FROM TABELA_DE_CLIENTES ORDER BY NOME;

